#!/bin/sh
# Githelper is released under the Expat/MIT license.
# Read the full text of the license in the file named
# "LICENSE" in this software distribution.

CURDIR=$(pwd) #Get working directory to later show so a user knows if he's in the right one.
echo "========="
echo "GITHELPER"
echo "========="
echo ""
echo "Using the $CURDIR repository."
echo -n "Enter commit description:"
read DESCRIPTION
echo ""

#Add all files in the repository to prepare for a commit
echo "Adding all changed files..."
git add .

#Do the actual commit with the DESCRIPTION variable as the description
echo "Commiting..."
git commit -m "$DESCRIPTION"

#Well, push to the remote repository, of course!
echo "Pushing to remote repository..."
git push

echo ""
echo "All done. Thank you."